const ADD_ROW = 'ADD_ROW';
const VISUALIZE_ROWS_LIST = 'VISUALIZE_ROWS_LIST';
const UPDATE_ROW = 'UPDATE_ROW';
const UPDATE_RESULTS = 'UPDATE_RESULTS';
const DELETE_ROW = 'DELETE_ROW';

export {
  ADD_ROW,
  VISUALIZE_ROWS_LIST,
  UPDATE_ROW,
  UPDATE_RESULTS,
  DELETE_ROW,
};
